[2024-09-11T08:58:04.399+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-11T08:58:04.414+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: welcome_dag.test manual__2024-09-11T08:45:16.827592+00:00 [queued]>
[2024-09-11T08:58:04.420+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: welcome_dag.test manual__2024-09-11T08:45:16.827592+00:00 [queued]>
[2024-09-11T08:58:04.421+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-09-11T08:58:04.432+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): test> on 2024-09-11 08:45:16.827592+00:00
[2024-09-11T08:58:04.447+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=676) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-11T08:58:04.449+0000] {standard_task_runner.py:72} INFO - Started process 678 to run task
[2024-09-11T08:58:04.449+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'welcome_dag', 'test', 'manual__2024-09-11T08:45:16.827592+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/welcome.py', '--cfg-path', '/tmp/tmpc59prmt_']
[2024-09-11T08:58:04.450+0000] {standard_task_runner.py:105} INFO - Job 38: Subtask test
[2024-09-11T08:58:04.492+0000] {task_command.py:467} INFO - Running <TaskInstance: welcome_dag.test manual__2024-09-11T08:45:16.827592+00:00 [running]> on host 9ac4da4c6d5e
[2024-09-11T08:58:04.557+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='welcome_dag' AIRFLOW_CTX_TASK_ID='test' AIRFLOW_CTX_EXECUTION_DATE='2024-09-11T08:45:16.827592+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-11T08:45:16.827592+00:00'
[2024-09-11T08:58:04.558+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-11T08:58:04.558+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-11T08:58:04.559+0000] {logging_mixin.py:190} INFO - Current task name:test state:running start_date:2024-09-11 08:58:04.415167+00:00
[2024-09-11T08:58:04.559+0000] {logging_mixin.py:190} INFO - Dag name:welcome_dag and current dag run status:running
[2024-09-11T08:58:04.560+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-11T08:58:04.569+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/welcome.py", line 157, in test
    net = data['net']
          ~~~~^^^^^^^
KeyError: 'net'
[2024-09-11T08:58:04.579+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-11T08:58:04.579+0000] {logging_mixin.py:190} INFO - Task start:2024-09-11 08:58:04.415167+00:00 end:2024-09-11 08:58:04.578691+00:00 duration:0.163524
[2024-09-11T08:58:04.579+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): test> dag:<DAG: welcome_dag> dagrun:<DagRun welcome_dag @ 2024-09-11 08:45:16.827592+00:00: manual__2024-09-11T08:45:16.827592+00:00, state:running, queued_at: 2024-09-11 08:45:16.843454+00:00. externally triggered: True>
[2024-09-11T08:58:04.580+0000] {logging_mixin.py:190} INFO - Failure caused by 'net'
[2024-09-11T08:58:04.580+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=welcome_dag, task_id=test, run_id=manual__2024-09-11T08:45:16.827592+00:00, execution_date=20240911T084516, start_date=20240911T085804, end_date=20240911T085804
[2024-09-11T08:58:04.589+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-11T08:58:04.590+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 38 for task test ('net'; 678)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/welcome.py", line 157, in test
    net = data['net']
          ~~~~^^^^^^^
KeyError: 'net'
[2024-09-11T08:58:04.624+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-11T08:58:04.639+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-11T08:58:04.641+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
